Fix a bunch of shell warnings in scripts.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -1,6 +1,6 @@
 #!/bin/bash
 set -e
-cd "`dirname \"$0\"`/.."
+cd "$(dirname "$0")/.."
 
 cd test
 
@@ -11,20 +11,20 @@ virtualenv --version > /dev/null || (echo "virtualenv must be installed"; exit 1
 
 for version in 2 3; do
   rm -rf venv-$version
-  virtualenv --python=`which python$version` venv-$version
+  virtualenv --python="$(which python$version)" "venv-$version"
   source venv-$version/bin/activate
   pip install --upgrade ../
 
   # runs a test file with PASS/FAIL message
   run_test() {
-    python $1 && echo "PASS $1 (Python $version)" || (echo "FAIL $1 (Python $version)"; exit 1)
+    (python "$1" && echo "PASS $1 (Python $version)") || (echo "FAIL $1 (Python $version)"; exit 1)
   }
 
   if [ "$1" == "" ]; then
-    for test in $(ls *.py); do
-      run_test $test
+    for test in *.py; do
+      run_test "$test"
     done
   else
-    run_test $1.py
+    run_test "$1.py"
   fi
 done
