Quiet test run and make passing tests more obvious.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 set -e
 cd "`dirname \"$0\"`/.."
 
@@ -10,10 +10,15 @@ virtualenv venv
 source venv/bin/activate
 pip install ../
 
+# runs a test file with PASS/FAIL message
+run_test() {
+  python $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
+}
+
 if [ "$1" == "" ]; then
   for test in $(ls *.py); do
-    python $test
+    run_test $test
   done
 else
-  python $1.py
+  run_test $1.py
 fi
